OMFG
Signed-off-by: Sound Chaser <davep.git@meduseld.net>

diff --git a/bin/dp-vnc-viewer b/bin/dp-vnc-viewer
--- a/bin/dp-vnc-viewer
+++ b/bin/dp-vnc-viewer
@@ -107,21 +107,118 @@ Usage_error()
 # xit vncviewer chicxulub
 #
 
-: ${VIEWER:=vncviewer}
+# Set defaults.
+: ${VNCVIEWER:=vncviewer}
 : ${VNCSERVER:=chicxulub}
-: ${XIT=xit}
+: ${XIT=}
+: ${loopp:=false}
+: ${invertp:=false}
+: ${keep_going_p=true}
+: ${num_loops=100}
 
-EExec_verbose_echo_id VNCSERVER XIT
+EExec_verbose_echo_id VIEWER VNCSERVER XIT
 
-[[ -n "${1-}" ]] && {
+# Usage variable usage:
+Usage_args_info=' Set $Usage_args_info'
+Usage_synopsis='Usage_synopsis.  Set $Usage_synopsis'
+# Idiom:
+# Using ) after the args makes copy & paste between here and the
+# case statement easier.
+# Who the FUCK is ever going to read this?
+# send an email to davep.i-read-a-comment@meduseld.net
+# [ as of: 2021-06-17T01:28:39 ] this is a working domain name email address.
+# But domains expire, dunnaye?
+Usage_details="${EExec_parse_usage}
+-o) flag o
+-O <val>) set Option to <val>
+"
+# Example of arg parsing.
+# NB: See eexec(dp), but [ as of: 2021-07-13T12:37:13 ]
+# -n, -v, -q, -nk, --nk, -vk, --vk and some --eexec-* option names are taken.
+# @todo XXX Remove as many as possible.  Too many aliases is one of my many
+# failings.
+# NB: -x is reserved for script-x
+option_str="lkis:c:xm:"
+declare -a long_options
+long_options=(
+    # E.g. loop until the command fails.
+    "loop-till-failure" "ltf"	# -l
+    # loop until then command succeeds.
+    "invert" "inv"		# -i
+    # loop-till-failure + invert
+    "keep-going"		# -k
+    # specify server.
+    "server:"			# -s
+    # client
+    "client:"			# -c
+    # use XIT
+    "xit"			# -x
+    # max loop count
+    "max:" "loops:" "max-loops:" "num-loops:" # -m
+)
+DP_IMPORTING_P=true source dp-getopt+.sh || exit 1
+EExec_verbose_msg "after dp-getopt+.sh: \$@>$@<"
+while (($# > 0))
+do
+  # do. e.g.  shift; $OPTION_ARG=$1;; # to process options with arguments.
+  case $1 in
+      # eexec support: -n -v -q, etc. q.v. ~/bin/eexec
+      # Done by EExec_parse and friends.
+
+      # Program options.
+      -l|--loop-till-failure|--ltf) loopp=true;;
+      -i|--invert|--inv) invertp=true;;
+      -k|--keep-going) keep_going_p=true;;
+      -s|--server) shift; VNCSERVER="${1}";;
+      -c|--client) shift; VNCVIEWER="${1}";;
+      -x|--xit) XIT=xit;;
+      -m|--nl|--max|--loops|--max-loops|--num-loops|--nl) shift; num_loops="${1}";;
+      # Help!
+      --help) Usage; exit 0;;
+      --) shift ; break ;;
+      # getopt will barf about unknown options.
+      # Here we barf about known options that we have forgotten to handle.
+      *) echo 1>&2 "Unhandled option>$1<"
+         exit 1;;
+    esac
+    shift
+done
+(($# > 0)) && {
+    # Arg beats option.
     VNCSERVER="${1}"
     shift
 }
+"${invertp}" && {
+    if "${loopp}"
+    then
+	loopp=false
+    else
+	loopp=true
+    fi
+}
 
 # No -s for type in BASH :-(.
-# Got blindsided when I forgot about the alternatives system.
-# It's a good one, as long I remember about when the universe thinks it'll
+# Got blindsided when I forgot about the alternatives system.  ps(1) never
+# showed the vncviewer I thought I was using.
+# It's a good one, as long I remember about it when the universe thinks it'll
 # help me.
-EExec_verbose_exec type  "${VIEWER}"
+#EExec_verbose_exec type  "${VNCVIEWER}"
+while true
+do
+    # @todo XXX Using xit is not recommended because it'll spawn processed
+    # speedy quick.  Can't even get to a console.
+    # It also loops like mad when EExec is in -n mode EExecDashN_p
+    EExec ${XIT} "${VNCVIEWER}" "${VNCSERVER}"
+    EExecDashN_p && {
+	EExec_verbose_msg "I'm not going to loop forever because you're using -n."
+	exit 3			# Or break --> returns 0.
+    } 1>&2 
+    ((--num_loops))
+    ((num_loops <= 0)) && break
+    #  Maybe break if XIT used?
+    rc="$?"
+    "${keep_going_p}" && continue
+    "${loopp}" && [[ "${rc}" != 0 ]] && break
+done
 
-EExec ${XIT} "${VIEWER}" "${VNCSERVER}"
+exit 0
diff --git a/bin/dp_decode_cmd_status b/bin/dp_decode_cmd_status
--- a/bin/dp_decode_cmd_status
+++ b/bin/dp_decode_cmd_status
@@ -1,29 +1,24 @@
 #!/usr/bin/env bash
 
-# Magic sourced binary->function
-# Can/should be set up thus:
-# alias dp_decode_cmd_status='unalias dp_decode_cmd_status; source dp_decode_cmd_status'
-
-# In case we're called by mistaek.
-# This is utter bullshit.
-[[ "$(type -t dp_decode_cmd_status 1>/dev/null 2>&1)" == function ]] && {
-    echo 1>&2 "dp_decode_cmd_status: already a function :-("
-    dp_decode_cmd_status "$@"
-}
-
+# Decode a program's exit code.
+# E.g. < 128 is a return code.
+#      > 128 is a signal error code.
+#      == 128 looks like 0, no I make it pseudoSIG0, since 128 isn't zero,
+#      but looks like it after mod'ing.
 function dp_decode_cmd_status()
 {
-    echo 1>&2 "enter: function: dp_decode_cmd_status: $(eko $@)"
-    local rc="${1-0}"; shift
+    #echo "===========\$?>$?<=========="
+    local prefix=""
+    [[ "$1" == "--zsh" ]] && {
+	prefix="<"
+	shift
+    }
+    local rc="${1-$?}"; shift
     local signum_min=128
     local signame="SIGNAME_UNSET"
     local signum=$((${rc} - ${signum_min}))
-    # echo 1>&2 "signum>${signum}<"
     local num_sigs=$(/bin/kill -l | wc -w)
-    echo 1>&2 "rc>${rc}<"
-    echo 1>&2 "signum>${signum}<"
-    echo 1>&2 "num_sigs>${num_sigs}<"
-    read -p "Enter plz..."
+    local pstr="pstr UNSET!"
 
     # User return codes should not be >= 128.
     if (("${rc}" <= "${signum_min}"))
@@ -31,50 +26,35 @@ function dp_decode_cmd_status()
 	# Special case to separate 128 from 0 (128 - 128)
 	if [[ "${rc}" == "${signum_min}" ]]
 	then
-	    echo "pseudoSIG0"
+	    # @todo XXX Is this a good idea?
+	    # This is informational only, anyway.
+	    pstr="pseudoSIG0"
 	else
-	    echo "${rc}"
+	    pstr="${rc}"
 	fi
 	rc="${rc}"
     elif ((${signum} > ${num_sigs}))
     then
 	# Is the signum > max signum?
-	echo "$rc:Illegal SIGNUM"
+	pstr="Illegal SIGNUM:$rc"
 	rc=1
     elif  signame=$(/bin/kill -l "${signum}") 2>/dev/null
     then
-	#echo 1>&2 "signame>${signame}<"
 	# Did kill find the signum pleasing?
 	# We already know the code isn't too big.
 	# zsh and bash have builtin kill commands that display
 	# the list of signals differently.
-	echo "SIG${signame}"
+	pstr="SIG${signame}"
 	rc=0
     else
-	echo "${rc}: EINVAL: confuzed"
+	pstr="${rc}: EINVAL: confuzed"
 	# Eat the effing rc, MFer.
 	# rc=$rc
     fi
+    echo "${prefix}${pstr}"
     # Eat the effing rc, MFer.
     return "${rc}"
 }
-DP_EXPORT_FUNC dp_decode_cmd_status
 
-echo "in file: dp_decode_cmd_status +++++++++++++++++"
-echo 1>&2 "dp_decode_cmd_status, \$0>$0<: $(type -t dp_decode_cmd_status)"
-echo "dp_decode_cmd_status, after export: $(eko $@)"
-# OK, I'll do it, but just this once.
-if [[ "${1-}" =~ ^--def(ine-only)?$ ]]
-then
-    # If we ever need more options.
-    shift;
-    echo 1>&2 "Defined only."
-    return 0
-else
-    dp_decode_cmd_status "$@"
-fi
-
-# BUT FOR SOME FUCKING reason using the alias in another script (e.g. func.root:)
-# always does.
-#echo 1>&2 "I shouldn't be here a-fucking-gain."
-echo 1>&2 "exiting file: dp_decode_cmd_status -----------------"
+# Makes it nice if I want to source this like a lib function
+dp_decode_cmd_status "$@"
