tto + finder of hashes (commits) of tags.

diff --git a/bin/faf2 b/bin/faf2
--- a/bin/faf2
+++ b/bin/faf2
@@ -1,5 +1,7 @@
 #!/bin/sh
 source script-x
+set -u
+progname=$(basename $0)
 
 # @ todo
 # fer-all-files [-FAF<opt>...] [find opts] [find args] [-- xargs opts]
@@ -7,10 +9,27 @@ source script-x
 # but?
 # fer-all-files -name '*mak' -- fgrep Mk
 
-option_str='vnqd:g:D:p:P:sf:'
-qdat=($(getopt -o "$option_str" -- "$@"))
-[ $? != 0 ] && Usage
-# is eval needed? eval set -- "${qdat[@]}" NO!
+DEF_FINDER=find
+
+Usage()
+{
+    echo \
+"Usage: $0 [find-args] -- [xargs-args]
+A simpler way to do the common op: find <fstuff> -print0 | xargs -r0 <xstuff>
+-s|--standard-finder -- Use $DEF_FINDER.
+(-f|--finder-prog) <prog> -- Use <prog> to find files.
+"
+}
+
+option_str='sf:'
+long_options_opt="--longoption=standard-finder --longoption=finder-prog:'"
+qdat=($(getopt -o "$option_str" $long_options_opt -- "$@"))
+rc=$?
+[ $rc != 0 ] && {
+    echo "Error from getopt: $rc"
+    Usage
+    exit $rc
+} 1>&2
 eval set -- "${qdat[@]}"
 
 vsetp "$DP_SCRIPT_X_DEBUG" && {
@@ -26,60 +45,49 @@ vsetp "$DP_SCRIPT_X_DEBUG" && {
 dirs=
 type=f
 
-[ $? != 0 ] && Usage
-
 RUNNER=runnit
 RUNNER1="$RUNNER"
 RUNNER2="$RUNNER"
-#POTENTIAL_FINDERS="find-sans-svn find"
+#POTENTIAL_FINDERS="find-sans-vc find"
 # Finders in order of preference.  First one found wins.
 POTENTIAL_FINDERS="find"
 FINDER=$(find-bin $POTENTIAL_FINDERS)
-FIND_PRE_ARGS_a=()
-FIND_POST_ARGS_a=()
-PATS_a=()
-dirs_a=()
 pipe='|'
 FIND_PRINT0_OPT="-print0"
 XARGS_PRINT0_OPT="-0"
 : ${XARGS_OPTS=-r}
-show_cmd=
-echo "0: @>$@<"
+${DP_SCRIPT_X_DEBUG_ONLY_ECHO_STDERR} "0: @>$@<"
 for i in "$@"
 do
     case "$1" in
-	-v) set -x;;		# Lazy^H^H^H^HPoor man's verbosity.
-	-q) ECHO=":" ;;
-	-d) dirs_a+=($2); shift;;   # Save off dirs.
-	-g) PATS_a+=($2); shift;;   # Save off globs.
-	-D) file=d; shift;;
-        -p) FIND_PRE_ARGS_a[${#FIND_PRE_ARGS_a[@]}]="$2"; shift;;
-        -P) FIND_POST_ARGS_a[${#FIND_POST_ARGS_a[@]}]="$2"; shift;;
-        -s) FINDER=find;;
+        -s) FINDER=$DEF_FINDER;; # Force use of the standard finder
         -f) FINDER=$2; shift;;
-        -n) show_cmd=t; RUNNER1=crappy_dash_n1; RUNNER2=crappy_dash_n2;;
-	--) break ;;
+	--) shift; break ;;
 	-*)
 	    echo 1>&2 "Unsupported option>$1<";
 	    exit 1 ;;
     esac
     shift
 done
-
+${DP_SCRIPT_X_DEBUG_ONLY_ECHO_STDERR} "1: @>$@<"
+#
+# xxx [xxx-args] -- [find-args] -- xargs-args
 # That sucked off all of our options.
 # All up to possible '--' are find args.
-# All after -- art xargs opts.
+# All after -- are xargs opts.
 find_args=()
 for j in "$@"
 do
-  echo_id j
-  echo "1>$1<"
+  #echo_id j
   case "$1" in
       --) shift; break;;
       *) find_args+=($1)
   esac
+  ${DP_SCRIPT_X_DEBUG_ONLY_ECHO_STDERR} "find_args>${find_args[@]}<find_args"
   shift
 done
+${DP_SCRIPT_X_DEBUG_ONLY_ECHO_STDERR} "2: @>$@<"
 xargs_args=("$@")
+${DP_SCRIPT_X_DEBUG_ONLY_ECHO_STDERR} "xargs_args>${find_args[@]}<xargs_args"
 
 $FINDER "${find_args[@]}" -print0 | xargs -r0 "${xargs_args[@]}"
