ssh changes

diff --git a/DOTrc/dp-ssh-agent b/DOTrc/dp-ssh-agent
--- a/DOTrc/dp-ssh-agent
+++ b/DOTrc/dp-ssh-agent
@@ -3,10 +3,11 @@
 #source script-x
 #set -x
 # These were clobbering each other across hosts.
-SSH_AGENT_RC="$HOME/.ssh/acmds.$HOSTNAME"
-SSH_AGENT_RC_STDERR="${SSH_AGENT_RC}.stderr"
-export SSH_AGENT_RC_umask=0077
-export SSH_AGENT_RC_STDERR_umask=${SSH_AGENT_RC_umask}
+DP_SSH_AGENT_RC="$HOME/.ssh/acmds.$HOSTNAME"
+DP_SSH_AGENT_RC_STDERR="${DP_SSH_AGENT_RC}.stderr"
+DP_SSH_AGENT_RC_LOG="${DP_SSH_AGENT_RC}.log"
+export DP_SSH_AGENT_RC_umask=0077
+export DP_SSH_AGENT_RC_STDERR_umask=${DP_SSH_AGENT_RC_umask}
 
 #wip dp_get_ssh_agent()
 #wip {
@@ -23,62 +24,106 @@ export SSH_AGENT_RC_STDERR_umask=${SSH_AGENT_RC_umask}
 #wip     }
 #wip }
 
-dp_add_default_keys()
+dp_ssh_add_default_keys()
 {
     ssh-add -l > /dev/null 2>&1
     local rc=$?
     case "$rc" in
-        0) true;;               # Got some, hopefully all, default keys.
-        1) ssh-add;;            # Agent up, no keys. Add defaults.
-        *) false;;              # No agent
+         # Some keys have been added. We won't do an ssh-add to get all
+         # because that will require us to re-enter any existing keys'
+         # passwords.
+        0) true;;
+        # Agent up, no keys. Add defaults, and return that op's status.
+        1) ssh-add;;
+        # No agent
+        *) false;;
     esac
 }
 
-# Really start or connect to ssh agent
-dp_start_ssh_agent()
+dp_ssh_add_keys()
 {
-    # Until I fix this whole concept.
-    [ -z "${SSH_AGENT_PID}" ] && {
-        eval $(ssh-agent)
-        export SSH_AGENT_PID
+    dp_ssh_add_default_keys && {
+        if [ -n "${DP_SSH_EXTRA_KEYS}" ]
+        then
+            ssh-add "${DP_SSH_EXTRA_KEYS}"
+        else
+            # Don't let the fact that DP_SSH_EXTRA_KEYS is not set look
+            # like a failure.
+            true
+        fi
     }
-    if [ -n "${SSH_AGENT_PID}" ]
-    then
-        dp_add_default_keys
-        local rc=$?
-        [ "$rc" = 0 ] && {      # No keys
-            [ -n "${DP_SSH_EXTRA_KEYS}" ] && {
-                ssh-add "${DP_SSH_EXTRA_KEYS}"
+}
+
+# Really start or connect to ssh agent
+dp_ssh_start_agent()
+{
+# Until I fix this whole concept.
+#what-was-wrong-before?     [ -z "${SSH_AGENT_PID}" ] && {
+#what-was-wrong-before?         eval $(ssh-agent)
+#what-was-wrong-before?         export SSH_AGENT_PID
+#what-was-wrong-before?     }
+#what-was-wrong-before?     if [ -n "${SSH_AGENT_PID}" ]
+#what-was-wrong-before?     then
+#what-was-wrong-before?         dp_add_default_keys
+#what-was-wrong-before?         local rc=$?
+#what-was-wrong-before?         [ "$rc" = 0 ] && {      # No keys
+#what-was-wrong-before?             [ -n "${DP_SSH_EXTRA_KEYS}" ] && {
+#what-was-wrong-before?                 ssh-add "${DP_SSH_EXTRA_KEYS}"
+#what-was-wrong-before?             }
+#what-was-wrong-before?         }
+#what-was-wrong-before?     else
+#what-was-wrong-before?         # We tried to start ssh-agent and failed.
+#what-was-wrong-before?         return 1
+#what-was-wrong-before?     fi
+#what-was-wrong-before?     return 0
+
+    {
+        date
+        env | fgrep SSH
+        echo_id DP_SSH_AGENT_RC
+        # See if there's a running agent to which we are attached.
+        dp_ssh_add_keys && {
+            echo "Using existing agent."
+            return 0
+        }
+
+        # See if we can attach to one started elsewhere.
+        [ -e "${DP_SSH_AGENT_RC}" ] && {
+            # Use last set of agent variables.
+            echo "--- ${DP_SSH_AGENT_RC} ---"
+            cat "${DP_SSH_AGENT_RC}"
+            echo "--- ${DP_SSH_AGENT_RC} ---"
+            source "${DP_SSH_AGENT_RC}" || {
+                echo "Error sourcing ${DP_SSH_AGENT_RC}"
+                return 3
+            }
+            # Try to add keys.
+            dp_ssh_add_keys && {
+                echo "Reconnecting to existing agent."
+                return 0
             }
         }
-    else
-        # We tried to start ssh-agent and failed.
-        return 1
-    fi
-    return 0
-
-#for now     #env | fgrep SSH
-#for now     #echo_id SSH_AGENT_RC
-#for now     # See if there's a running agent to which we are attached.
-#for now     dp_add_default_keys && return 0
-
-#for now     # See if we can attach to one started elsewhere.
-#for now     [ -e "$SSH_AGENT_RC" ] && {
-#for now         # Use last set of agent variables.
-#for now         source "$SSH_AGENT_RC" || return 3
-#for now         # Try to add keys.
-#for now         dp_add_default_keys && return 0
-#for now     }
-#for now     # There isn't an agent already running that we can use, neither
-#for now     # configured in this shell nor one whose configuration info is in the
-#for now     # "$SSH_AGENT_RC"
-#for now     # So start one and save the configuration variables.
-#for now     ssh-agent | \fgrep -v echo >| "$SSH_AGENT_RC"
-#for now     # set those variables.
-#for now     source "$SSH_AGENT_RC" || return 3
-#for now     # If we can't set the keys, we're doomed.
-#for now     # Pass on the key command rc.
-#for now     dp_add_default_keys
+        echo "Trying to start new agent"
+        # There isn't an agent already running that we can use, neither
+        # configured in this shell nor one whose configuration info is in the
+        # "$DP_SSH_AGENT_RC"
+        # So start one and save the configuration variables.
+        ssh-agent | \fgrep -v echo >| "${DP_SSH_AGENT_RC}"
+        # and set them.
+        source "${DP_SSH_AGENT_RC}" || {
+            echo "Error sourcing ${DP_SSH_AGENT_RC} from new agent."
+            return 4
+        }
+        # If we can't set the keys, we're doomed.
+        # We'll pass on the key command rc whatever it is.
+        dp_ssh_add_keys
+        local rc="$?"
+        if [ "${rc}" != 0 ]
+        then
+            echo "Error adding keys to new agent."
+        fi
+        return "${rc}"
+    } >| "${DP_SSH_AGENT_RC_LOG}" 2>&1
 }
 
 [ -n "${runme-}" -o "$(basename -- $0)" = dp-ssh-agent ] && {
