WIP making add ssh agent work properly.

diff --git a/DOTrc/dp-ssh-agent b/DOTrc/dp-ssh-agent
--- a/DOTrc/dp-ssh-agent
+++ b/DOTrc/dp-ssh-agent
@@ -8,6 +8,21 @@ SSH_AGENT_RC_STDERR="${SSH_AGENT_RC}.stderr"
 export SSH_AGENT_RC_umask=0077
 export SSH_AGENT_RC_STDERR_umask=${SSH_AGENT_RC_umask}
 
+#wip dp_get_ssh_agent()
+#wip {
+#wip     ssh-add -l > /dev/null 2>&1
+#wip     local rc=$?
+#wip     case "$rc" in
+#wip         # Up and happy or up and empty
+#wip         0|1) echo "SSH_AGENT_PID"; true; return;;
+#wip     esac
+#wip     local possible_pid=$(dpgrep -p ssh-agent | head -n1)
+#wip     [ -z "${possible_pid}" ] && {
+#wip         # No ssh-agent we can talk to.
+#wip         return 1
+#wip     }
+#wip }
+
 dp_add_default_keys()
 {
     ssh-add -l > /dev/null 2>&1
@@ -27,16 +42,19 @@ dp_start_ssh_agent()
         eval $(ssh-agent)
         export SSH_AGENT_PID
     }
-    [ -n "${SSH_AGENT_PID}" ] && {
-        ssh-add -l > /dev/null 2>&1
+    if [ -n "${SSH_AGENT_PID}" ]
+    then
+        dp_add_default_keys
         local rc=$?
-        [ "$rc" = 1 ] && {      # No keys
-            ssh-add             # Add defaults
+        [ "$rc" = 0 ] && {      # No keys
             [ -n "${DP_SSH_EXTRA_KEYS}" ] && {
                 ssh-add "${DP_SSH_EXTRA_KEYS}"
             }
         }
-    }
+    else
+        # We tried to start ssh-agent and failed.
+        return 1
+    fi
     return 0
 
 #for now     #env | fgrep SSH
