2b|!2b -->1

diff --git a/bin.nvidia/index-me-code b/bin.nvidia/index-me-code
--- a/bin.nvidia/index-me-code
+++ b/bin.nvidia/index-me-code
@@ -129,7 +129,10 @@ then
 fi
 
 [ -z "$ap_dir" ] && {
-    ap_dir=$(find-ap-dir)
+    ap_dir=$(find-ap-dir) || {
+        echo "Cannot find ap dir."
+        exit 1
+    } 1>&2
 }
 
 [ -d "${ap_dir}" ] || {
@@ -202,11 +205,15 @@ depot_dirs_of_interest="$base_depot_dirs_of_interest $more_depot_dirs_of_interes
 
 other_dirs_of_interest=""
 
+echo_id2 ap_dir
+echo_id2 ap_path
+echo_id2 ap_hw_p4_path
 echo_id2 p4_root
+
 dirs_of_interest=$(dp4-reroot "$p4_root" $depot_dirs_of_interest)
 dirs_of_interest="${dirs_of_interest} ${other_dirs_of_interest}"
 
-[ -z "${skip_cd_p}" ] && EExec -y mecd sandbox
+vsetp "${skip_cd_p}" || EExec -y mecd sandbox
 dp_echo2 "cwd: $(pwd)"
 
 # These files change and come and go and are mostly copies of existing files.
diff --git a/bin.nvidia/run-one-tgen b/bin.nvidia/run-one-tgen
--- a/bin.nvidia/run-one-tgen
+++ b/bin.nvidia/run-one-tgen
@@ -29,6 +29,7 @@ mecd testgen
 : ${last_and_latest_prefix=}
 : ${hist_file_name=$(basename $0).hist}
 : ${mailto_opt=}
+: ${sandbox_opt=-nosandbox}
 
 # Usage variable usage:
 Usage_args_info=" <tgen-level-test>..."
@@ -156,7 +157,7 @@ done
 : ${clobber_opt=-clobber}
 : ${levels:=${user_levels:-${default_level}}}
 : ${traceRoot_opt=/home/scratch.traces02/arch/traces/}
-: ${chip_opt=t124}
+: ${chip_opt="?"}
 : ${target_opt=FMODEL}
 : ${user_log_dir=}
 : ${log_dir_base=dp-run-tgens.d} # This is duplicated in tgen-latest-run. Make a tgen.rc type file.
@@ -198,6 +199,17 @@ vsetp "${d_opt}" || {
 }
 d_opt=$(normpath "${d_opt}")/
 
+if [ "${chip_opt}" = '?' ]
+then
+    case "$PWD" in
+        */ap_t132/*) chip_opt=t132;;
+        */ap_t124/*|*/ap_tlit1/*) chip_opt=t124;;
+        *) echo 1>&2 "Cannot guess chip type based on current directory:
+$PWD"
+           exit 1;;
+    esac
+fi
+
 # Appending to $@ allows for more kinds of quoting to be preserved.
 vsetp "${queue}" && set -- "$@" -queue "${queue}"
 vsetp "$traceRoot_opt}" ] && set -- "$@" -traceRoot "${traceRoot_opt}"
@@ -206,6 +218,7 @@ vsetp "$target_opt}"  && set -- "$@" -target "${target_opt}"
 vsetp "$d_opt}" ] && set -- "$@" -d "${d_opt}"
 vsetp "${all_but_run_opt}" && set -- "$@" "${all_but_run_opt}"
 vsetp "${mailto_opt}" && set -- "$@" ${mailto_opt}
+vsetp "${sandbox_opt}" && set -- "$@" ${sandbox_opt}
 log_prefix="$log_dir"
 
 [ -n "$display_status_p" -a -z "$wait_opt" ] && {
@@ -310,6 +323,6 @@ done
 
 vsetp "${all_but_run_opt}" && {
     echo "
-*** $progname: -allButRun was used.
+++++ $progname: -allButRun was used.
   Don't forget to run them if you need to."
 } 1>&2
diff --git a/bin.nvidia/tgen-run-dot-sh-logged b/bin.nvidia/tgen-run-dot-sh-logged
--- a/bin.nvidia/tgen-run-dot-sh-logged
+++ b/bin.nvidia/tgen-run-dot-sh-logged
@@ -19,7 +19,7 @@ EExecVerbose
 : ${p4_clib_dir:=//hw/ap_tlit1/clib/Linux}
 : ${log_file_base_name:=dot-sh}
 # I'm done with bash because the quoting sucks beyond suckage:
-# --egrep 'ERROR: cannot aquire /tmp/asim.X' 
+# --egrep 'ERROR: cannot aquire /tmp/asim.X'
 # --egrep 'something bad happened'}
 # --cflush-every=-1 --> flush to zip every line.
 : ${teeker_options=--slog -Z9 --ts --hg -i100 --cflush-every=-1}
@@ -29,11 +29,19 @@ check_test()
 {
     local testname="$@"
     local rc=1
-    if test -d "${testname}"
-    then 
+
+    echo "Checking test candidate>$@<"
+    if [ -z "${testname}" ]
+    then
+        echo 'testname is empty'
+    elif (($(echo "$@" | wc -w) > 1))
+    then
+        echo "More than one executable file found."
+    elif test -d "${testname}"
+    then
         echo "${testname} is a dir."
     elif ! test -x "${testname}"
-    then 
+    then
         echo "${testname} is not executable."
     else
         rc=0
@@ -43,24 +51,31 @@ check_test()
 
 if vunsetp "${testname}"
 then
-    case "${1-}" in 
+    case "${1-}" in
         -|.|--) shift;;
         -*|"") ;;
         *) testname="${1}"; shift ;;
     esac
     vunsetp "${testname}" && {
-        testname=$(ls -1 *.sh | egrep -v '^(command|.*\.cmd)\.sh$')
-        if vunsetp "${testname}" || ! test -x "${testname}" || test -d "${testname}"
+        # In a dir like:
+        # /home/scratch.dpanariti_t124_1/sb3/sb3hw/hw/ap_t132/diag/testgen/dp-run-tgens.d/swr_so_runlimit/2013-08-16T18.26.17-0400.out/tests/kepler_b_ogtest/00/00/01/000001
+        testname=$(pwd | sed -rn 's!(^.*/dp-run-tgens.d/)([^/]+)(/.*)!\2!p')
+        #echo_id testname
+        vsetp "${testname}" && testname="${testname}.sh"
+        if ! check_test "$testname"
         then
-            echo "$progname: No test name given and cannot guess a good default.
+            testname=$(ls -1 *.sh | egrep -v '^(command|.*\.cmd)\.sh$')
+            #echo_id testname
+            if ! check_test "${testname}"
+            then
+                echo "$progname: No test name given and cannot guess a good default.
 Usage:  testname [additional-teeker-options]"
-            check_test "${testname}"
-            exit 1
-        fi 1>&2
+                exit 1
+            fi 1>&2
+        fi
         echo "Deduced test name>${testname}<"
     }
 fi
-check_test "${testname}" 1>&2 || exit 1
 test_base_name=$(basename "${testname}" .sh)
 cfg_file_name="${test_base_name}.cfg"
 so_name=$(sed -rn "s/(.*-plugin ')([^[:space:]]+)( .*)/\2/p" "${cfg_file_name}").so
