sigh

diff --git a/bin.nvidia/index-me-code b/bin.nvidia/index-me-code
--- a/bin.nvidia/index-me-code
+++ b/bin.nvidia/index-me-code
@@ -1,5 +1,19 @@
 #!/bin/sh
 
+#
+# Index code. ME used to mean Multiengine, but that's not the only thing done
+# now.
+# There are two basic entities:
+# 1) database locations - db-locs
+#    Places where cscope and global databases reside.
+# 2) directories of interests - doi dois dsoi
+#    Trees we wish to index
+#
+# For each db-loc, any doi under it is added to db-loc's db.
+#
+# The entities can be SB relative names.
+#
+
 source script-x
 set -u
 progname="$(basename $0)"
@@ -27,7 +41,48 @@ export eexec_program
 source $HOME/.rc/env.nvidia
 : ${db_locs=${DP_NV_ME_DB_LOCS=ap //arch //sw/dev //sw/mods //sw/tools //hw/class //hw/kepler1_gklit3 //hw/tools}}
 : ${db_loc_excludes=}
+: ${hw_ap_p=t}
+: ${me_tests_p=t}
+: ${manuals_p=t}
+: ${more_depot_dirs_p=t}
+: ${hw_dirs_p=t}
+: ${sw_dirs_p=t}
+: ${fmod_dirs_p=t}
+: ${make_script_p=t}
+: ${script_name=}
+: ${bg_p=}
 
+run_it()
+{
+    local bg_p="${1}"
+    shift
+    local run_dir="${1}"
+    shift
+    local script_opts=
+
+    if vsetp "${script_name}"
+    then
+        script_opts="--sh-cd --sh: ${script_name}"
+    elif true_p "${make_script_p}"
+    then
+        script_opts="--sh-cd --sh: ${progname}-eexec.sh"
+    fi
+    
+    EExec_verbose_echo_id script_opts
+
+    (
+        cd "${db_loc}"
+        EExec_verbose_echo_id --msg 'Indexing in: ' PWD
+        if true_p "${bg_p}"
+        then
+            EExec ${script_opts} "$@" &
+        else
+            EExec ${script_opts} "$@"
+        fi
+    )
+}
+        
+        
 #WTF? nvcscope_filter()
 #WTF? {
 #WTF?     egrep -v '/ap(_tlit[0-9]/'
@@ -116,7 +171,11 @@ long_options=(
 "skip-cd" "stay-put" "oot" "cron"
 "exclude-db-loc:"
 "add-db-loc:"
-"init-db-loc:")
+"init-db-loc:"
+"bg"
+"make-script"
+"no-script" "no-make-script"
+"script-name")
 source dp-getopt+.sh
 for i in "$@"
 do
@@ -135,6 +194,10 @@ do
       -e|--exclude-db-loc) shift; db_loc_excludes="${db_loc_excludes} ${1}";;
       -a|--add-db-loc) shift; db_locs="${db_locs} ${1}";;
       -i|--init-db-loc) shift; db_locs="${1}";;
+      --bg) bg_p=t;;
+      --make-script) make_script_p=t;;
+      --no-script|--no-make-script) make_script_p=;;
+      --script-name) shift; script_name="${1}"; make_script_p=t;;
       # Help!
       --help) Usage; exit 0;;
       --) shift ; break ;;
@@ -154,14 +217,17 @@ fi
 [ -z "$ap_dir" ] && {
     ap_dir=$(find-ap-dir) || {
         echo "Cannot find ap dir."
+        echo " Cannot index any ap sub-directories."
+    } 1>&2
+}
+EExec_verbose_echo_id ap_dir
+
+vsetp "${ap_dir}" && {
+    [ -d "${ap_dir}" ] || {
+        dp_echo "ap_dir>${ap_dir}<, isn't."
         exit 1
     } 1>&2
 }
-
-[ -d "${ap_dir}" ] || {
-    dp_echo "ap_dir>${ap_dir}<, isn't."
-    exit 1
-} 1>&2
 
 vsetp "${skip_cd_p}" || EExec -y mecd sandbox
 dp_echo2 "cwd: $(pwd)"
@@ -193,18 +259,27 @@ ap_gpu_me_inf="//hw/ap/ip/inf/gpu_multiengine/1.0"
 # /home/scratch.dpanariti_t124/t124_0/arch/traces/mobile/traces/gpu_multiengine/sanity_bsea/sanity_bsea.cpp
 
 pre_t210_gpu_me_tests="
-//arch/traces/mobile/traces/gpu_multiengine/
+//arch/traces/mobile/traces/gpu_multiengine/"
+pre_t210_non_gpu_me_tests="
 //arch/traces/mobile/traces/nongpu_multiengine/"
+pre_t210_me_tests="
+${pre_t210_gpu_me_tests}
+${pre_t210_non_gpu_me_tests}"
 
 t210_gpu_me_tests="
 ${ap_gpu_me_inf}/clib/gpu_multiengine"
+t210_non_gpu_me_tests=""            # ??? Where be them?
+t210_me_tests="
+${t210_gpu_me_tests}
+${t210_non_gpu_me_tests}"
 
 chip=$(guess-chip)
 EExec_verbose_msg "guessed $(echo_id chip)"
 case "${chip}" in
-    t210) gpu_me_tests="${t210_gpu_me_tests}";;
-    t124|t132) gpu_me_tests="${pre_t210_gpu_me_tests}";;
-    *) echo 1>&2 "Unknown chip>${chip}<, exiting."; exit 1;;
+    t210) me_tests="${t210_me_tests}";;
+    t124|t132) me_tests="${pre_t210_gpu_tests}";;
+    *) echo 1>&2 "Unknown chip>${chip}<, bagging me_tests."
+       me_tests_p=;;
 esac
 
 #
@@ -213,12 +288,28 @@ esac
 #
 ### Files out of source tree when using /home/scratch.traces02/mobile/traces/system/so/
 ### Tried to do it at root, but it makes things relative to root, e.g. /home/x --> home/x
-base_depot_dirs_of_interest="
+depot_dirs_of_interest=""
+
+if vtruep "${hw_ap_p}"
+then
+    depot_dirs_of_interest="
+${depot_dirs_of_interest}
 ${ap_hw_p4_path}/drv/drvapi/
 ${ap_hw_p4_path}/drv/multiengine/
-${ap_hw_p4_path}/inf/mods/trace_3d/plugin/
-${gpu_me_tests}
+${ap_hw_p4_path}/inf/mods/trace_3d/plugin/"
+fi
+
+if vtruep "${me_tests_p}"
+then
+    depot_dirs_of_interest=="${depot_dirs_of_interest} ${me_tests}"
+fi
+
+if vtruep "${manuals_p}"
+then
+    depot_dirs_of_interest="
+${depot_dirs_of_interest} 
 //hw/kepler1_gklit3/manuals/"
+fi
 
 # too big: //hw/${ap_dir}/include/
 # Taken care of with NOTAG files.
@@ -228,13 +319,24 @@ ${gpu_me_tests}
 # order dependence sucks.
 
 # Adding //hw/${ap_dir}/clib causes (error Rerun etags...) problems.
-more_depot_dirs_of_interest="
+if vtruep "${more_depot_dirs_p}"
+then
+    depot_dirs_of_interest="
+${depot_dirs_of_interest}
 ${ap_hw_p4_path}/include/
 ${ap_hw_p4_path}/ip/vdec/cmod/
 ${ap_hw_p4_path}/drv/simfront/
 ${ap_hw_p4_path}/drv/bootrom/
 ${ap_hw_p4_path}/drv/chiplib/
 ${ap_hw_p4_path}/clib/
+${ap_hw_p4_path}/tools/RunScript/
+${ap_hw_p4_path}/bin/"
+fi
+
+if vtruep "${hw_dirs_p}"
+then
+    depot_dirs_of_interest="
+${depot_dirs_of_interest}
 //hw/class/
 //hw/oot/
 //hw/tools/mods
@@ -242,25 +344,34 @@ ${ap_hw_p4_path}/clib/
 //hw/kepler1_gklit3/clib/
 //hw/kepler1_gklit3/diag/
 //dev/cpu/tools/sim/asim/1.0/"
+fi
 
-sw_depot_dirs_of_interest="
+if vtruep "${sw_dirs_p}"
+then
+    depot_dirs_of_interest="
+${depot_dirs_of_interest}
 //sw/dev/
 //sw/mods/
 //sw/tools/"
+fi
 
-depot_dirs_of_interest="${base_depot_dirs_of_interest} ${more_depot_dirs_of_interest} ${sw_depot_dirs_of_interest}"
+if vtruep "${fmod_dirs_p}"
+then
+    depot_dirs_of_interest="
+${depot_dirs_of_interest}
+$(me-expand-dest --normpath-term fmod)"
+fi
 
 other_dirs_of_interest=""
 
-echo_id2 ap_dir
-echo_id2 ap_path
-echo_id2 ap_hw_p4_path
-echo_id2 p4_root
+EExec_verbose_echo_id ap_dir
+EExec_verbose_echo_id ap_path
+EExec_verbose_echo_id ap_hw_p4_path
+EExec_verbose_echo_id p4_root
 
 dirs_of_interest=$(dp4-reroot "$p4_root" $depot_dirs_of_interest)
 dirs_of_interest="${dirs_of_interest} ${other_dirs_of_interest}"
-echo_id2 dirs_of_interest
-
+EExec_verbose_echo_id dirs_of_interest
 
 # These files change and come and go and are mostly copies of existing files.
 # This kind of stuff confuses cscope.
@@ -277,13 +388,13 @@ then
     # //hw/ap_tlit1/drv/multiengine/framework/utilities/loader/stream_loader.cpp
     # H0w can any thing be s0 fncking stnpid?
     ap_hw_path=$(dp4-reroot "$p4_root" "${ap_hw_p4_path}")
-    #echo_id2 ap_hw_p4_path
-    #echo_id2 ap_hw_path
-    #echo_id2 dirs_of_interest
+    #EExec_verbose_echo_id ap_hw_p4_path
+    #EExec_verbose_echo_id ap_hw_path
+    #EExec_verbose_echo_id dirs_of_interest
     # Filter out dirs here so we don't even look inside them.
     # Remove the ap tree since nvcscope already handles it.
     dirs_of_interest=$(filter_dirs "${ap_hw_path}" ${dirs_of_interest})
-    #echo_id2 dirs_of_interest
+    #EExec_verbose_echo_id dirs_of_interest
     (
         link_em=t
         cd "${ap_path}"
@@ -311,7 +422,7 @@ for exclude in ${db_loc_excludes}
 do
   db_locs=$(echo "${db_locs}" | sed -r "s! $exclude !!")
 done
-echo_id2 db_locs
+EExec_verbose_echo_id db_locs
 #exit 99
 
 if ! true_p "${just_nvcscope_p}"
@@ -321,43 +432,54 @@ then
     for db_loc in ${db_locs}
     do
       index_dirs=
-      #echo_id2 db_loc
-      #db_loc=$(dp4-reroot . "${db_loc}")
       db_loc=$(me-expand-dest "${db_loc}")
-      #echo_id2 db_loc
+      EExec_verbose_echo_id --msg 'Examining: ' db_loc
       [ -d "${db_loc}" ] || continue
       for doi in ${dirs_of_interest}
       do
-#         echo_id2 doi
-#         echo_id2 db_loc
+        EExec_verbose_echo_id db_loc doi
         # Select the dirs of interest under this db_loc
+        # See if the dir exists or if an mexpansion of it does.
+        # @todo XXX We may want to try the mexpansion first.
+        [ -e "${doi}" ] || {
+            continue
+            # We'll just make it a requirement that any abbrevs be expanded
+            # when they're added to the list of doi,s.  In many cases it is
+            # expected that a lot of doi,s won't be present, and expansion
+            # takes too much time.
+            EExec_verbose_echo_id --msg "Non-existent: " doi
+            doi=$(me-expand-dest --normpath-term "${doi}")
+            EExec_verbose_echo_id --msg 'mexpanded: ' doi
+            [ -e "${doi}" ] || continue
+            EExec_verbose_echo_id --msg 'using mexpanded: ' doi
+        }
         case "${doi}/" in
             $db_loc/*) index_dirs="${index_dirs}
 ${doi}";;
-            *) ;; #echo "no match>$doi<";;
+            *) EExec_verbose_echo_id --msg "no match: " doi;;
         esac
       done
       vunsetp "${index_dirs}" && {
           dp_echo2 "*** No dirs for db_loc>$db_loc< ***"
           continue
       }
-#       echo_id2 db_loc
-#       echo_id2 index_dirs
+      EExec_verbose_echo_id db_loc
+      EExec_verbose_echo_id index_dirs
       all_indexed="${all_indexed}
 >${index_dirs}<"
-      cd "${db_loc}"
-      echo_id2 PWD
-      EExec index-code $follow_links_arg $index_dirs
+      run_it "${bg_p}" "${db_loc}" index-code $follow_links_arg $index_dirs
       all_db_locs="${all_db_locs} ${db_loc}"
     done
-    echo_id2 dirs_of_interest
-    echo_id2 all_indexed
-    echo_id2 all_db_locs
+    EExec_verbose_echo_id dirs_of_interest
+    EExec_verbose_echo_id all_indexed
+    EExec_verbose_echo_id all_db_locs
 
     index_out_of_tree_locations
 else
     dp_echo "Not indexing non-nvcscope code."
 fi
+
+wait
 
 vsetp "${send_mail_on_completion-}" && {
     EExec email-yopp ${cron_opt}
