fkinlrs

diff --git a/bin.nvidia/tgen-latest-run b/bin.nvidia/tgen-latest-run
--- a/bin.nvidia/tgen-latest-run
+++ b/bin.nvidia/tgen-latest-run
@@ -11,6 +11,7 @@ source eexec
 : ${printor=echo}
 : ${log_dir_base=dp-run-tgens.d} # This is duplicated from tgen-run-one. Make a tgen.rc type file.
 : ${print_base_dir_p=}
+: ${test_dir_glob=}
 
 # Usage variable usage:
 Usage_args_info=" [test-number]"
@@ -24,7 +25,7 @@ Usage_details="${EExec_parse_usage}
 --realpath|--rp) Use realpath(1) to show dir.
 "
 # Example of arg parsing.
-option_str="${EExec_parse_option_str}rb"
+option_str="${EExec_parse_option_str}rbg:"
 # long_options=("option-name-without-leading--" ...)
 long_options=("test-name:" "testname:" "name:" "tn:"
 "no-cd" "stay-put" "." "no-mecd-testgen"
@@ -32,6 +33,7 @@ long_options=("test-name:" "testname:" "name:" "tn:"
 "base-dir" "root-dir" "base" "root"
 "test-type:" "type:" "out:"
 "sb:" "sandbox:" "tree:"
+"test-dir-glob:"
 )
 
 source dp-getopt+.sh
@@ -51,6 +53,8 @@ do
       -r|--realpath) printor=realpath;;
       --sb|--sandbox|--tree) shift; mecd_to="${1}";;
       --test-type|--type|--out) shift; some_path_component="${1}";;
+      -g) shift; test_dir_glob="*${1}*";;
+      --test-dir-glob) shift; test_dir_glob="${1}";;
       # Help!
       --help) Usage; exit 0;;
       --) shift ; break ;;
@@ -59,7 +63,6 @@ do
     esac
     shift
 done
-
 
 prefix=
 vsetp "${1-}" && {
@@ -96,19 +99,46 @@ else
 fi
 
 #some_path_component=$(echo $(cat last_out_dir)/tests/*)
-: ${some_path_component=$(echo ${latest_out_dir}/tests/*)}
+vunsetp "${some_path_component-}" && {
+    some_path_component=$(find ${latest_out_dir}/tests -type d)
+}
+EExec_verbose_echo_id some_path_component
+EExec_verbose_msg "some_path_component glob: >${latest_out_dir}/tests/*<"
+tmp_some_path_component=
+num_components=$(echo "${some_path_component}" | wc -l)
 case "${some_path_component}" in
-    *\ *) {
+    0) echo 1>&2 "Cannot find any components under ${latest_out_dir}/tests"; exit 1;;
+    1) break;;
+    *) {
              echo "Multiple test type dirs exist. Don't know which to use:"
+             if vsetp "${test_dir_glob}"
+             then
+                 echo "   Will select first match of>${test_dir_glob}<."
+             fi
              for d in ${some_path_component}
              do
+               EExec_verbose_echo_id d
                #echo " $(basename $d)"
-               echo " $(realpath $d)"
+               dir_rp="$(realpath $d)"
+               EExec_verbose_echo_id dir_rp
+               if vsetp "${test_dir_glob-}"
+               then
+                   EExec_verbose_echo "applying glob: $(echo_id test_dir_glob)"
+                   case "$dir_rp" in
+                       ${test_dir_glob}) tmp_some_path_component="${dir_rp}"; break;;
+                       *) ;;
+                   esac
+               fi
              done
           } 1>&2
-          exit 1;;
-    *) ;;
+          vunsetp "${tmp_some_path_component}" && {
+              echo "*** Try a unique glob: --test-dir-glob <glob>"
+              exit 1
+       }
+       some_path_component="${tmp_some_path_component}"
+       dest="${some_path_component}";;
 esac
+EExec_verbose_echo_id some_path_component
 some_path_component=$(basename $some_path_component)
 
 EExec_verbose_echo_id latest_out_dir some_path_component first_dir_num second_dir_num
@@ -117,7 +147,7 @@ if vsetp "${print_base_dir_p}"
 then
     "${printor}" "${latest_out_dir}"
 else
-    dest="${latest_out_dir}/tests/${some_path_component}/00/00/${first_dir_num}/${second_dir_num}"
+    vunsetp "${dest}" && dest="${latest_out_dir}/tests/${some_path_component}/00/00/${first_dir_num}/${second_dir_num}"
     "${printor}" "${dest}"
     [ -d "${dest}" ] # Print the value, but set status based on its actual existence.
 fi
